title: Perspective, Hgeun
author: Park Hyeon Geun
email: hgeun1447@sogang.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  Computer Vision Engineer.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Park Hyeon Geun
  tagline: Developer. Computer-Vision. 
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "KR" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
  # generate social links in footer
  social_links:
    github: Hgeun
    email: "hgeun1447@sogang.ac.kr"
  
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
 # - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
